### ISSUE TITLE
error converting YAML to JSON: did not find expected key

### ISSUE THREAD

**Issue by kamilikamil** [stcox/charts#10]
Hey I am actually trying to run the `helm install -f ./wp-sites/mysite-com.yaml ./gkewordpress/wordpress`

But I keep getting this: `error converting YAML to JSON: yaml: line 36: did not find expected key`

Either I am not specifying the correct `dbCred{}` in `values.yaml` or my syntax is wrong.

1.  I created the Services Account from IAM pointing to SQL Cloud database by going to this link https://console.cloud.google.com/iam-admin/serviceaccounts?project=your-project and then the JSON key I got I populated the `dbCred{}` in `values.yaml`. So this is wrong.

2. I will share how I am stating the `dbCred{}` in `values.yaml`. Maybe my syntax is wrong: 

```
dbCred: {
  type: '',
  project_id: '',
  private_key_id: '',
  private_key: '',
  client_email: '',
  client_id: '',
  auth_uri: '',
  token_uri: '',
  auth_provider_x509_cert_url: '',
  client_x509_cert_url: '',
}

```

If anyone can help me. It will be really appreciated :)

**Comment by kamilikamil** [comment]
Alright, so I made changes to the `secrets.yaml` file and `values.yaml` file.

dbCred value in `secrets.yaml` file:

```
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-instance-credentials
  namespace: wp-{{ .Values.name }}
  labels:
    app: wp-{{ .Values.name }}
type: Opaque
data:
  credentials.json: {{ toJson .Values.dbCred | b64enc }}
```


`Values.yaml` file:

```
dbCred: {
  'type': '',
  'project_id': '',
  'private_key_id': '',
  'private_key': '-----BEGIN PRIVATE KEY-----\n-----END PRIVATE KEY-----\n',
  'client_email': '',
  'client_id': '',
  'auth_uri': '',
  'token_uri': '',
  'auth_provider_x509_cert_url': '',
  'client_x509_cert_url': ''
}
```

helm install works now. But now the wp is not able to connect to MYSQL.

Attatching the screenshot of the logs.

![image](https://user-images.githubusercontent.com/43093536/49732720-f0cd1200-fc98-11e8-8b98-715da8b1abe9.png)
